import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    header: {
      topexSchool: 'Topex School',
      tagline: 'Education of a New Generation',
      home: 'Home',
      about: 'About',
      programs: 'Programs',
      teachers: 'Teachers',
      gallery: 'Gallery',
      news: 'News',
      comparison: 'Comparison',
      contact: 'Contact',
      login: 'Login',
      register: 'Register',
      myProfile: 'My Profile',
      logout: 'Logout',
      adminPanel: 'Admin Panel',
    },
    footer: {
      aboutSchool: 'Leading educational school of a new generation, providing quality education and development for every student.',
      quickLinks: 'Quick Links',
      about: 'About School',
      programs: 'Programs',
      teachers: 'Teachers',
      admission: 'Admission',
      contacts: 'Contacts',
      phone: 'Phone',
      email: 'Email',
      address: 'Address',
      socialMedia: 'Follow Us',
      subscribeNews: 'Subscribe to News',
      getUpdates: 'Get the latest updates from Topex School',
      yourEmail: 'Your email',
      subscribe: 'Subscribe',
      allRights: 'All rights reserved.',
    },
    home: {
      tagline: 'Education of a New Generation',
      welcome: 'Welcome to',
      subtitle: 'Open the doors to a world of knowledge and opportunities with our revolutionary education system',
      explorePrograms: 'Explore Programs',
      contactUs: 'Contact Us',
      students: 'Students',
      teachers: 'Teachers',
      programs: 'Programs',
      successRate: 'Success Rate',
      innovativeEdu: 'Innovative Education',
      innovativeDesc: 'Advanced teaching methods using AI and modern technologies',
      bestTeachers: 'Best Teachers',
      bestTeachersDesc: 'Team of experts with international certificates and experience',
      worldStandards: 'World Standards',
      worldStandardsDesc: 'Programs meet the best educational systems',
      talentDev: 'Talent Development',
      talentDevDesc: 'Personal development path for each student',
    },
    about: {
      title: 'About Topex School',
      subtitle: 'Over 14 years of excellence in education',
      ourStory: 'Our Story',
      storyText1: 'Topex School was founded in 2010 with a mission to provide students with world-class education. Over the years, we have grown from a small school to a leading educational institution.',
      storyText2: 'Our school is known for innovative teaching methods, highly qualified teachers, and modern infrastructure.',
      storyText3: 'Today, Topex School is more than 5000 students, 150+ teachers, and 50+ educational programs.',
      yearsExperience: 'years of experience',
      ofStudents: 'of students',
      ofTeachers: 'of teachers',
      admissions: 'admissions',
      ourMission: 'Our Mission',
      missionText: 'Providing quality education, developing the talents and abilities of each student, preparing them for a successful career in the modern world.',
      ourVision: 'Our Vision',
      visionText: 'To become a leading educational organization recognized for innovation, quality of teaching, and contribution to society.',
      ourValues: 'Our Values',
      quality: 'Quality',
      qualityDesc: 'Highest standard of education',
      care: 'Care',
      careDesc: 'Individual approach to each person',
      development: 'Development',
      developmentDesc: 'Continuous improvement',
      team: 'Team',
      teamDesc: 'United team of professionals',
      achievements: 'Our Achievements',
    },
    programs: {
      title: 'Our Programs',
      subtitle: '50+ diverse programs for comprehensive development',
      primarySchool: 'Primary School',
      primaryDesc: 'Comprehensive program for children with emphasis on creativity and foundational skills development',
      middleSchool: 'Middle School',
      middleDesc: 'In-depth study with individual learning trajectories and specialized electives',
      highSchool: 'High School',
      highSchoolDesc: 'Advanced preparation for the best universities in the world with AP and IB programs',
      programming: 'Programming & IT',
      programmingDesc: 'Modern programming languages, web development, mobile apps and AI fundamentals',
      languages: 'Foreign Languages',
      languagesDesc: 'English, German, French, Chinese with native speakers and immersion methods',
      mathematics: 'Advanced Mathematics',
      mathematicsDesc: 'In-depth study of calculus, algebra, geometry and mathematical olympiads',
      arts: 'Arts & Design',
      artsDesc: 'Painting, graphic design, sculpture, digital art and contemporary creative practices',
      music: 'Music & Performing Arts',
      musicDesc: 'Piano, guitar, violin, vocals, music theory and ensemble performance',
      duration: 'Duration',
      level: 'Level',
      students: 'Students',
      grades: 'Grades',
      allLevels: 'All levels',
      flexible: 'Flexible schedule',
      advanced: 'Advanced level',
      startDate: 'Start date',
      instructor: 'Instructor',
      capacity: 'Capacity',
      enrolled: 'Enrolled',
      description: 'Description',
      curriculum: 'Curriculum',
      requirements: 'Requirements',
    },
    teachers: {
      title: 'Our Teachers',
      name: 'Name',
      position: 'Position',
      subject: 'Subject',
      bio: 'Biography',
      director: 'Director',
      seniorTeacher: 'Senior Teacher',
      teacher: 'Teacher',
      pedagogics: 'Pedagogy',
      mathPhysics: 'Mathematics and Physics',
      docScience: 'Candidate of Physics and Mathematics Sciences',
      languages: 'Foreign Languages',
      certifiedSpecialist: 'Certified CELTA Specialist',
      programming: 'Programming',
      itExperience: '15 years of experience in IT industry',
      literature: 'Literature and Russian Language',
      masterArts: 'Master of Philology',
      chemistry: 'Chemistry and Biology',
      researcher: 'Research Fellow',
      history: 'History and Geography',
      publications: 'Author of scientific publications',
      sports: 'Physical Education',
      sportsMaster: 'Master of International Class',
      art: 'Art and Design',
      artist: 'Professional Artist',
      experience: 'years of experience in education',
    },
    gallery: {
      title: 'Gallery',
      subtitle: 'See the life of Topex School through photos',
      all: 'All',
      campus: 'Campus',
      classes: 'Classes',
      events: 'Events',
      sports: 'Sports',
      mainBuilding: 'Main Building',
      library: 'Library',
      classroom: 'Classroom',
      lab: 'Laboratory',
      groupWork: 'Group Work',
      graduation: 'Graduation',
      exhibition: 'Exhibition',
      event: 'Event',
      gymnasium: 'Gymnasium',
      football: 'Football',
      computerLab: 'Computer Lab',
      building: 'Building',
    },
    news: {
      title: 'News',
      subtitle: 'Follow the latest events of Topex School',
      readFull: 'Read Full Article',
      subscribeNews: 'Subscribe to Newsletter',
      getUpdates: 'Get the latest updates from Topex School',
      youremail: 'Your email address',
      subscribe: 'Subscribe',
      achievements: 'Achievements',
      events: 'Events',
      partnerships: 'Partnerships',
      newsCategory: 'Category',
      newsDate: 'Published',
      newsAuthor: 'Author',
      back: 'Back to News',
      latestNews: 'Latest News',
      viewMore: 'View More Articles',
      share: 'Share Article',
      related: 'Related Articles',
      newsContent: 'News Content',
    },
    contact: {
      title: 'Contacts',
      subtitle: 'Contact us in any convenient way',
      phone: 'Phone',
      email: 'Email',
      address: 'Address',
      sendMessage: 'Send us a Message',
      thankYou: 'Thank you! We received your message and will respond soon.',
      yourName: 'Your Name',
      emailLabel: 'Email',
      phoneLabel: 'Phone',
      subject: 'Subject',
      message: 'Message',
      send: 'Send',
      sending: 'Sending...',
      required: 'Required field',
      invalidEmail: 'Invalid email address',
    },
    login: {
      title: 'Login',
      email: 'Email',
      password: 'Password',
      login: 'Login',
      register: 'Don\'t have an account? Register',
      forgot: 'Forgot password?',
      error: 'Invalid email or password',
    },
    register: {
      title: 'Register',
      fullName: 'Full Name',
      email: 'Email',
      phone: 'Phone',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      register: 'Create Account',
      haveAccount: 'Already have an account? Login',
      passwordMatch: 'Passwords do not match',
      success: 'Registration successful! Redirecting...',
      error: 'An error occurred. Please try again later.',
      nameError: 'Please enter your full name',
      emailError: 'Please enter your email',
      emailInvalid: 'Invalid email address',
      phoneError: 'Please enter your phone number',
      passwordError: 'Please enter your password',
      passwordShort: 'Password must be at least 6 characters',
      selectRole: 'Select Role',
      selectSubject: 'Select Subject',
      roleRequired: 'Please select a role',
      subjectRequired: 'Please select a subject',
    },
    admin: {
      title: 'Admin Panel',
      dashboard: 'Dashboard',
      users: 'Users',
      teachers: 'Teachers',
      students: 'Students',
      news: 'News',
      ratings: 'Ratings',
      income: 'Income',
      settings: 'Settings',
      profile: 'Profile',
      logout: 'Logout',
      totalUsers: 'Total Users',
      activeUsers: 'Active Users',
      newThisWeek: 'New This Week',
      newThisMonth: 'New This Month',
      monthlyRegistrations: 'Monthly Registrations',
      weeklyRegistrations: 'Weekly Registrations',
      userStatus: 'User Status',
      active: 'Active',
      inactive: 'Inactive',
      banned: 'Banned',
      loading: 'Loading statistics...',
      error: 'Error loading statistics',
      addNews: 'Add News',
      deleteNews: 'Delete News',
      editNews: 'Edit News',
      newsTitle: 'Title',
      newsContent: 'Content',
      newsImage: 'Image URL',
      newsCategory: 'Category',
      save: 'Save',
      cancel: 'Cancel',
      confirmDelete: 'Are you sure you want to delete?',
      myRating: 'My Rating',
      ratingHistory: 'Rating History',
      activityPoints: 'Activity Points',
      attendancePoints: 'Attendance Points',
      totalPoints: 'Total Points',
      position: 'Position',
      teacherRankings: 'Teacher Rankings',
      myIncome: 'My Income',
      monthlyIncome: 'Monthly Income',
      yearlyIncome: 'Yearly Income',
      bonuses: 'Bonuses',
      deductions: 'Deductions',
      netIncome: 'Net Income',
      accessDenied: 'Access Denied',
      noPermission: 'You do not have permission to view this section',
      manageUsers: 'Manage Users',
      addUser: 'Add User',
      editUser: 'Edit User',
      deleteUser: 'Delete User',
      role: 'Role',
      subject: 'Subject',
      phone: 'Phone',
      email: 'Email',
      name: 'Name',
      actions: 'Actions',
      search: 'Search',
      filter: 'Filter',
      all: 'All',
      director: 'Director',
      viceDirector: 'Vice Director',
      teacher: 'Teacher',
      student: 'Student',
    },
    common: {
      language: 'Language',
      english: 'English',
      russian: 'Русский',
      uzbek: "O'zbek",
      loading: 'Loading...',
      back: '← Back to home',
      ok: 'OK',
      cancel: 'Cancel',
      close: 'Close',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
    },
    roles: {
      director: 'Director',
      vice_director: 'Vice Director',
      teacher: 'Teacher',
      student: 'Student',
    },
    subjects: {
      programming: 'Programming',
      design: 'Design',
      business: 'Business',
      hotel_business: 'Hotel Business',
      marketing: 'Marketing',
      laboratory: 'Laboratory',
      english: 'English',
      mathematics: 'Mathematics',
      russian: 'Russian',
      history: 'History',
    },
  },
  ru: {
    header: {
      topexSchool: 'Topex School',
      tagline: 'Образование нового поколения',
      home: 'Главная',
      about: 'О нас',
      programs: 'Программы',
      teachers: 'Преподаватели',
      gallery: 'Галерея',
      news: 'Новости',
      comparison: 'Сравнение',
      contact: 'Контакты',
      login: 'Вход',
      register: 'Регистрация',
      myProfile: 'Мой профиль',
      logout: 'Выход',
      adminPanel: 'Админ панель',
    },
    footer: {
      aboutSchool: 'Ведущая образовательная школа нового поколения, предоставляющая качественное обучение и развитие для каждого студента.',
      quickLinks: 'Быстрые ссылки',
      about: 'О школе',
      programs: 'Программы',
      teachers: 'Преподаватели',
      admission: 'Поступление',
      contacts: 'Контакты',
      phone: 'Телефон',
      email: 'Email',
      address: 'Адрес',
      socialMedia: 'Мы в соцсетях',
      subscribeNews: 'Подпишитесь на новости',
      getUpdates: 'Получайте последние обновления школы',
      yourEmail: 'Ваш email',
      subscribe: 'Подписаться',
      allRights: 'Все права защищены.',
    },
    home: {
      tagline: 'Образование нового поколения',
      welcome: 'Добро пожаловать в',
      subtitle: 'Откройте двери в мир знаний и возможностей с нашей революционной системой образования',
      explorePrograms: 'Исследуйте программы',
      contactUs: 'Связаться с нами',
      students: 'Студентов',
      teachers: 'Преподавателей',
      programs: 'Программ',
      successRate: 'Успеваемость',
      innovativeEdu: 'Инновационное образование',
      innovativeDesc: 'Передовые методы обучения с использованием AI и современных технологий',
      bestTeachers: 'Лучшие педагоги',
      bestTeachersDesc: 'Команда экспертов с международными сертификатами и опытом',
      worldStandards: 'Мировые стандарты',
      worldStandardsDesc: 'Программы соответствуют лучшим образовательным системам',
      talentDev: 'Развитие талантов',
      talentDevDesc: 'Персональный путь развития для каждого студента',
    },
    about: {
      title: 'О школе Topex',
      subtitle: 'Более 14 лет превосходства в образовании',
      ourStory: 'Наша история',
      storyText1: 'Topex School была основана в 2010 году с миссией предоставить студентам образование мирового уровня. За годы работы мы выросли из небольшой школы в ведущее образовательное учреждение.',
      storyText2: 'Наша школа известна инновационными методами обучения, высококвалифицированными преподавателями и современной инфраструктурой.',
      storyText3: 'Сегодня Topex School - это более 5000 студентов, 150+ преподавателей и 50+ образовательных программ.',
      yearsExperience: 'лет опыта',
      ofStudents: 'студентов',
      ofTeachers: 'педагогов',
      admissions: 'поступлений',
      ourMission: 'Наша миссия',
      missionText: 'Предоставлять качественное образование, развивать таланты и способности каждого студента, готовить их к успешной карьере в современном мире.',
      ourVision: 'Наше видение',
      visionText: 'Стать ведущей образовательной организацией, признанной за инновации, качество обучения и вклад в развитие общества.',
      ourValues: 'Наши ценности',
      quality: 'Качество',
      qualityDesc: 'Высочайший стандарт образования',
      care: 'Забота',
      careDesc: 'Индивидуальный подход каждому',
      development: 'Развитие',
      developmentDesc: 'Постоянное совершенствование',
      team: 'Команда',
      teamDesc: 'Сплоченный коллектив профи',
      achievements: 'Наши достижения',
    },
    programs: {
      title: 'Наши программы',
      subtitle: '50+ разнообразных программ для всестороннего развития',
      primarySchool: 'Начальная школа',
      primaryDesc: 'Комплексная программа для детей с акцентом на креативность и развитие фундаментальных навыков',
      middleSchool: 'Средняя школа',
      middleDesc: 'Углубленное изучение с индивидуальными траекториями обучения и специализированными факультативами',
      highSchool: 'Старшая школа',
      highSchoolDesc: 'Подготовка к лучшим университетам мира с программами AP и IB',
      programming: 'Программирование и IT',
      programmingDesc: 'Современные языки программирования, веб-разработка, мобильные приложения и основы AI',
      languages: 'Иностранные языки',
      languagesDesc: 'Английский, немецкий, французский, китайский с носителями и методом погружения',
      mathematics: 'Высшая математика',
      mathematicsDesc: 'Углубленное изучение анализа, алгебры, геометрии и математических олимпиад',
      arts: 'Искусство и дизайн',
      artsDesc: 'Живопись, графический дизайн, скульптура, цифровое искусство и современные творческие практики',
      music: 'Музыка и сценическое искусство',
      musicDesc: 'Фортепиано, гитара, скрипка, вокал, музыкальная теория и ансамблевое исполнение',
      duration: 'Длительность',
      level: 'Уровень',
      students: 'Студентов',
      grades: 'классы',
      allLevels: 'Все уровни',
      flexible: 'Гибкий график',
      advanced: 'Продвинутый уровень',
      startDate: 'Дата начала',
      instructor: 'Преподаватель',
      capacity: 'Вместимость',
      enrolled: 'Зарегистрировано',
      description: 'Описание',
      curriculum: 'Учебный план',
      requirements: 'Требования',
    },
    teachers: {
      title: 'Наши преподаватели',
      name: 'Имя',
      position: 'Должность',
      subject: 'Предмет',
      bio: 'Биография',
      director: 'Директор',
      seniorTeacher: 'Старший преподаватель',
      teacher: 'Преподаватель',
      pedagogics: 'Педагогика',
      mathPhysics: 'Математика и физика',
      docScience: 'Кандидат физико-математических наук',
      languages: 'Иностранные языки',
      certifiedSpecialist: 'Сертифицированный специалист CELTA',
      programming: 'Программирование',
      itExperience: '15 лет опыта в IT индустрии',
      literature: 'Литература и русский язык',
      masterArts: 'Магистр филологических наук',
      chemistry: 'Химия и биология',
      researcher: 'Научный сотрудник НИИ',
      history: 'История и география',
      publications: 'Автор научных публикаций',
      sports: 'Физическая культура',
      sportsMaster: 'Мастер спорта международного класса',
      art: 'Искусство и дизайн',
      artist: 'Профессиональный художник',
      experience: 'лет опыта в образовании',
    },
    gallery: {
      title: 'Галерея',
      subtitle: 'Посмотрите на жизнь Topex School через фотографии',
      all: 'Все',
      campus: 'Кампус',
      classes: 'Учебный процесс',
      events: 'Мероприятия',
      sports: 'Спорт',
      mainBuilding: 'Главное здание',
      library: 'Библиотека',
      classroom: 'Программирование',
      lab: 'Лаборатория',
      groupWork: 'Групповая работа',
      graduation: 'Выпускной',
      exhibition: 'Выставка',
      event: 'Мероприятие',
      gymnasium: 'Спортзал',
      football: 'Футбол',
      computerLab: 'Компьютерный класс',
      building: 'Корпус',
    },
    news: {
      title: 'Новости',
      subtitle: 'Следите за последними событиями Topex School',
      readFull: 'Читать полную статью',
      subscribeNews: 'Подпишитесь на рассылку',
      getUpdates: 'Получайте последние обновления Topex School',
      youremail: 'Ваш адрес email',
      subscribe: 'Подписаться',
      achievements: 'Достижения',
      events: 'Мероприятия',
      partnerships: 'Партнерство',
      newsCategory: 'Категория',
      newsDate: 'Опубликовано',
      newsAuthor: 'Автор',
      back: 'Назад к новостям',
      latestNews: 'Последние новости',
      viewMore: 'Просмотреть все статьи',
      share: 'Поделиться статьей',
      related: 'Похожие статьи',
      newsContent: 'Содержание новости',
    },
    contact: {
      title: 'Контакты',
      subtitle: 'Свяжитесь с нами любым удобным способом',
      phone: 'Телефон',
      email: 'Email',
      address: 'Адрес',
      sendMessage: 'Отправьте нам сообщение',
      thankYou: 'Спасибо! Мы получили ваше сообщение и ответим вскоре.',
      yourName: 'Ваше имя',
      emailLabel: 'Email',
      phoneLabel: 'Телефон',
      subject: 'Тема',
      message: 'Сообщение',
      send: 'Отправить',
      sending: 'Отправка...',
      required: 'Обязательное поле',
      invalidEmail: 'Неверный адрес email',
    },
    login: {
      title: 'Вход',
      email: 'Email',
      password: 'Пароль',
      login: 'Войти',
      register: 'Нет аккаунта? Зарегистрироваться',
      forgot: 'Забыли пароль?',
      error: 'Неверный email или пароль',
    },
    register: {
      title: 'Регистрация',
      fullName: 'Полное имя',
      email: 'Email',
      phone: 'Телефон',
      password: 'Пароль',
      confirmPassword: 'Подтвердите пароль',
      register: 'Создать аккаунт',
      haveAccount: 'Уже есть аккаунт? Войти',
      passwordMatch: 'Пароли не совпадают',
      success: 'Регистрация успешна! Перенаправление...',
      error: 'Произошла ошибка. Попробуйте позже.',
      nameError: 'Введите полное имя',
      emailError: 'Введите email',
      emailInvalid: 'Некорректный email',
      phoneError: 'Введите номер телефона',
      passwordError: 'Введите пароль',
      passwordShort: 'Пароль должен быть минимум 6 символов',
      selectRole: 'Выберите роль',
      selectSubject: 'Выберите предмет',
      roleRequired: 'Выберите роль',
      subjectRequired: 'Выберите предмет',
    },
    admin: {
      title: 'Админ Панель',
      dashboard: 'Главная',
      users: 'Пользователи',
      teachers: 'Учителя',
      students: 'Ученики',
      news: 'Новости',
      ratings: 'Рейтинги',
      income: 'Доходы',
      settings: 'Настройки',
      profile: 'Профиль',
      logout: 'Выход',
      totalUsers: 'Всего пользователей',
      activeUsers: 'Активные пользователи',
      newThisWeek: 'Новые на этой неделе',
      newThisMonth: 'Новые в этом месяце',
      monthlyRegistrations: 'Регистрации по месяцам',
      weeklyRegistrations: 'Регистрации по неделям',
      userStatus: 'Статус пользователей',
      active: 'Активные',
      inactive: 'Неактивные',
      banned: 'Заблокированные',
      loading: 'Загрузка статистики...',
      error: 'Ошибка при загрузке статистики',
      addNews: 'Добавить новость',
      deleteNews: 'Удалить новость',
      editNews: 'Редактировать новость',
      newsTitle: 'Заголовок',
      newsContent: 'Содержание',
      newsImage: 'URL изображения',
      newsCategory: 'Категория',
      save: 'Сохранить',
      cancel: 'Отмена',
      confirmDelete: 'Вы уверены, что хотите удалить?',
      myRating: 'Мой рейтинг',
      ratingHistory: 'История рейтинга',
      activityPoints: 'Очки за активность',
      attendancePoints: 'Очки за посещаемость',
      totalPoints: 'Общие очки',
      position: 'Позиция',
      teacherRankings: 'Рейтинг учителей',
      myIncome: 'Мой доход',
      monthlyIncome: 'Месячный доход',
      yearlyIncome: 'Годовой доход',
      bonuses: 'Бонусы',
      deductions: 'Удержания',
      netIncome: 'Чистый доход',
      accessDenied: 'Доступ запрещен',
      noPermission: 'У вас нет прав для просмотра этого раздела',
      manageUsers: 'Управление пользователями',
      addUser: 'Добавить пользователя',
      editUser: 'Редактировать пользователя',
      deleteUser: 'Удалить пользователя',
      role: 'Роль',
      subject: 'Предмет',
      phone: 'Телефон',
      email: 'Email',
      name: 'Имя',
      actions: 'Действия',
      search: 'Поиск',
      filter: 'Фильтр',
      all: 'Все',
      director: 'Директор',
      viceDirector: 'Завуч',
      teacher: 'Учитель',
      student: 'Ученик',
    },
    common: {
      language: 'Язык',
      english: 'English',
      russian: 'Русский',
      uzbek: "O'zbek",
      loading: 'Загрузка...',
      back: '← Вернуться на главную',
      ok: 'OK',
      cancel: 'Отмена',
      close: 'Закрыть',
      darkMode: 'Тёмная тема',
      lightMode: 'Светлая тема',
    },
    roles: {
      director: 'Директор',
      vice_director: 'Завуч',
      teacher: 'Учитель',
      student: 'Ученик',
    },
    subjects: {
      programming: 'Программирование',
      design: 'Дизайн',
      business: 'Бизнес',
      hotel_business: 'Отельный бизнес',
      marketing: 'Маркетинг',
      laboratory: 'Лаборант',
      english: 'Английский язык',
      mathematics: 'Математика',
      russian: 'Русский язык',
      history: 'История',
    },
  },
  uz: {
    header: {
      topexSchool: 'Topex School',
      tagline: "Yangi Avlodning Ta'limi",
      home: 'Bosh sahifa',
      about: 'Haqida',
      programs: 'Dasturlar',
      teachers: "O'qituvchilar",
      gallery: 'Galereya',
      news: 'Yangiliklar',
      comparison: 'Solishtiruv',
      contact: 'Aloqa',
      login: 'Kirish',
      register: "Ro'yxatdan o'tish",
      myProfile: 'Mening profilim',
      logout: 'Chiqish',
      adminPanel: 'Admin panel',
    },
    footer: {
      aboutSchool: "Har bir talaba uchun sifatli ta'lim va rivojlantirishni taqdim etuvchi yangi avlod ta'lim maktabi.",
      quickLinks: 'Tez havolalar',
      about: 'Maktab haqida',
      programs: 'Dasturlar',
      teachers: "O'qituvchilar",
      admission: 'Qabul',
      contacts: 'Aloqa',
      phone: 'Telefon',
      email: 'Email',
      address: 'Manzil',
      socialMedia: "Biz bilan bog'lanish",
      subscribeNews: "Yangiliklarga obuna bo'lish",
      getUpdates: 'Topex School dan oxirgi yangiliklarni oling',
      yourEmail: 'Sizning email',
      subscribe: "Obuna bo'lish",
      allRights: 'Barcha huquqlar himoyalangan.',
    },
    home: {
      tagline: "Yangi Avlodning Ta'limi",
      welcome: 'Topex School ga xush kelibsiz',
      subtitle: "Bizning inqilobiy ta'lim tizimi bilan bilim va imkoniyatlar olamiga eshiklaringizni oching",
      explorePrograms: "Dasturlarni o'rganing",
      contactUs: "Biz bilan bog'lanish",
      students: 'Talabalar',
      teachers: "O'qituvchilar",
      programs: 'Dasturlar',
      successRate: 'Muvaffaqiyat darajasi',
      innovativeEdu: "Innovatsion ta'lim",
      innovativeDesc: "AI va zamonaviy texnologiyalardan foydalangan progressiv o'qitish usullari",
      bestTeachers: "Eng yaxshi o'qituvchilar",
      bestTeachersDesc: "Xalqaro sertifikatli va tajribali mutaxassislar jamoasi",
      worldStandards: 'Xalqaro standartlar',
      worldStandardsDesc: "Dasturlar eng yaxshi ta'lim tizimlariga mos keladi",
      talentDev: "Iste'dodni rivojlantirish",
      talentDevDesc: "Har bir talaba uchun shaxsiy rivojlanish yo'li",
    },
    about: {
      title: 'Topex Maktabi haqida',
      subtitle: "Ta'limda 14 yildan ortiq mukammallik",
      ourStory: 'Bizning hikoyamiz',
      storyText1: "Topex School 2010 yilda talabalar uchun jahon sinfining ta'limini ta'minlash maqsadi bilan tashkil etildi. Yillar o'tib, biz kichik maktabdan yetakchi ta'lim muassasasiga aylandik.",
      storyText2: "Bizning maktab innovatsion o'qitish usullari, yuqori malakali o'qituvchilar va zamonaviy infratuzilma bilan tanilgan.",
      storyText3: "Bugungi Topex School 5000 dan ortiq talaba, 150+ o'qituvchi va 50+ ta'lim dasturlari.",
      yearsExperience: 'yillik tajriba',
      ofStudents: 'talabalar',
      ofTeachers: "o'qituvchilar",
      admissions: 'qabul',
      ourMission: 'Bizning missiyamiz',
      missionText: "Sifatli ta'lim taqdim etish, har bir talabaning iste'dod va qobiliyatlarini rivojlantirish, ularni zamonaviy dunyoda muvaffaqiyatli karera uchun tayyorlash.",
      ourVision: "Bizning ko'rishimiz",
      visionText: "Innovatsiya, o'qitish sifati va jamiyat rivojlanishiga hissa qo'shgan holda tan olingan yetakchi ta'lim tashkiloti bo'lish.",
      ourValues: 'Bizning qadriyatlarimiz',
      quality: 'Sifat',
      qualityDesc: "Ta'limning eng yuqori standarti",
      care: "G'amxo'rlik",
      careDesc: "Har birga individual yondashuv",
      development: 'Rivojlanish',
      developmentDesc: 'Doimiy takomillashtirish',
      team: 'Jamoa',
      teamDesc: 'Birlashgan mutaxassislar jamoasi',
      achievements: 'Bizning yutuqlarimiz',
    },
    programs: {
      title: 'Bizning dasturlar',
      subtitle: "50+ turli dasturlar to'liq rivojlanish uchun",
      primarySchool: "Boshlang'ich maktab",
      primaryDesc: "Kreativlikka va asosiy ko'nikmalarga urg'u bergan bolalar uchun kompleks dastur",
      middleSchool: "O'rta maktab",
      middleDesc: "Individual ta'lim yo'li va ixtisoslashtirilgan fakultativlar bilan chuqur o'rganish",
      highSchool: "O'rta maxsus maktab",
      highSchoolDesc: 'AP va IB dasturlari bilan dunyodagi eng yaxshi universitetlar uchun tayyorlash',
      programming: 'Dasturlash va IT',
      programmingDesc: 'Zamonaviy dasturlash tillari, veb-ishlab chiqish, mobil ilovalar va AI asoslari',
      languages: 'Chet tillar',
      languagesDesc: "Ingliz, nemis, fransuz, xitoy ona tilida so'zlashuvchilar va immersion usuli bilan",
      mathematics: 'Yuqori matematika',
      mathematicsDesc: "Analiz, algebra, geometriya va matematik olimpiadalarning chuqur o'rganishi",
      arts: "San'at va dizayn",
      artsDesc: "Rasm, grafik dizayn, haykaltaroshlik, raqamli san'at va zamonaviy ijodiy amaliyotlar",
      music: "Musiqa va sahna san'ati",
      musicDesc: 'Royal, gitara, skripka, vokal, musiqa nazariyasi va ansambl ijrosi',
      duration: 'Davomiyligi',
      level: 'Daraja',
      students: 'Talabalar',
      grades: 'sinf',
      allLevels: 'Barcha darajalar',
      flexible: 'Moslashuvchan jadval',
      advanced: "Yuqori daraja",
      startDate: 'Boshlanish sanasi',
      instructor: "O'qituvchi",
      capacity: "Sig'imi",
      enrolled: "Ro'yxatga olindi",
      description: "Ta'rif",
      curriculum: "O'quv rejasi",
      requirements: 'Talablar',
    },
    teachers: {
      title: "Bizning o'qituvchilar",
      name: 'Ism',
      position: 'Lavozim',
      subject: 'Fan',
      bio: 'Tarjimai hol',
      director: 'Direktor',
      seniorTeacher: "Katta o'qituvchi",
      teacher: "O'qituvchi",
      pedagogics: 'Pedagogika',
      mathPhysics: 'Matematika va fizika',
      docScience: 'Fizika-matematik fanlar nomzodi',
      languages: 'Chet tillar',
      certifiedSpecialist: 'Sertifikatlangan CELTA mutaxassisi',
      programming: 'Dasturlash',
      itExperience: 'IT industriyasida 15 yillik tajriba',
      literature: 'Adabiyot va rus tili',
      masterArts: 'Filologiya magistri',
      chemistry: 'Kimyo va biologiya',
      researcher: 'Ilmiy tadqiqot instituti olimi',
      history: 'Tarix va geografiya',
      publications: 'Ilmiy nashrlarda muallif',
      sports: 'Jismoniy tarbiya',
      sportsMaster: 'Xalqaro sinf sport ustasi',
      art: "San'at va dizayn",
      artist: 'Professional rassom',
      experience: "ta'limda yillik tajriba",
    },
    gallery: {
      title: 'Galereya',
      subtitle: "Suratlar orqali Topex School hayotini ko'ring",
      all: 'Barchasi',
      campus: 'Kampus',
      classes: 'Dars jarayoni',
      events: 'Tadbirlar',
      sports: 'Sport',
      mainBuilding: 'Asosiy bino',
      library: 'Kutubxona',
      classroom: 'Dasturlash',
      lab: 'Laboratoriya',
      groupWork: 'Guruh ishi',
      graduation: 'Bitirish',
      exhibition: "Ko'rgazma",
      event: 'Tadbir',
      gymnasium: 'Sport zali',
      football: 'Futbol',
      computerLab: 'Kompyuter laboratoriyasi',
      building: 'Bino',
    },
    news: {
      title: 'Yangiliklar',
      subtitle: "Topex School ning oxirgi tadbirlarini kuzatib boring",
      readFull: "To'liq maqolani o'qish",
      subscribeNews: "Yangiliklar podkastiga obuna bo'lish",
      getUpdates: 'Topex School dan oxirgi yangiliklarni oling',
      youremail: 'Sizning email manzilingiz',
      subscribe: "Obuna bo'lish",
      achievements: 'Yutuqlar',
      events: 'Tadbirlar',
      partnerships: 'Hamkorlik',
      newsCategory: 'Kategoriya',
      newsDate: 'Chop etilgan',
      newsAuthor: 'Muallif',
      back: 'Yangiliklarni qaytarish',
      latestNews: 'Oxirgi yangiliklar',
      viewMore: "Barcha maqolalarni ko'rish",
      share: 'Maqolani ulashish',
      related: "O'xshash maqolalar",
      newsContent: 'Yangilik mazmuni',
    },
    contact: {
      title: 'Kontaktlar',
      subtitle: "Sizga qulay bo'lgan istalgan yo'l bilan biz bilan bog'laning",
      phone: 'Telefon',
      email: 'Email',
      address: 'Manzil',
      sendMessage: 'Bizga xabar yuboring',
      thankYou: 'Rahmat! Sizning xabaringizni oldik va tez orada javob beramiz.',
      yourName: 'Sizning ismingiz',
      emailLabel: 'Email',
      phoneLabel: 'Telefon',
      subject: 'Mavzu',
      message: 'Xabar',
      send: 'Yuborish',
      sending: 'Yuborilmoqda...',
      required: 'Talab qilinadigan maydon',
      invalidEmail: "Noto'g'ri email manzili",
    },
    login: {
      title: 'Kirish',
      email: 'Email',
      password: 'Parol',
      login: 'Kirish',
      register: "Akkaunt yo'qmi? Ro'yxatdan o'tish",
      forgot: 'Parolni unutdingizmi?',
      error: "Noto'g'ri email yoki parol",
    },
    register: {
      title: "Ro'yxatdan o'tish",
      fullName: "To'liq ism",
      email: 'Email',
      phone: 'Telefon',
      password: 'Parol',
      confirmPassword: 'Parolni tasdiqlang',
      register: 'Akkaunt yaratish',
      haveAccount: 'Akkaunt bormi? Kirish',
      passwordMatch: 'Parollar mos kelmadi',
      success: "Ro'yxatdan o'tish muvaffaqiyatli! Yo'naltirmoqda...",
      error: "Xato sodir bo'ldi. Keyinroq urinib ko'ring.",
      nameError: "Iltimos, to'liq ismingizni kiriting",
      emailError: 'Iltimos, emailingizni kiriting',
      emailInvalid: "Noto'g'ri email",
      phoneError: 'Iltimos, telefon raqamingizni kiriting',
      passwordError: 'Iltimos, parolni kiriting',
      passwordShort: "Parol kamida 6 belgidan iborat bo'lishi kerak",
      selectRole: 'Rolni tanlang',
      selectSubject: 'Fanni tanlang',
      roleRequired: 'Rolni tanlang',
      subjectRequired: 'Fanni tanlang',
    },
    admin: {
      title: 'Admin Panel',
      dashboard: 'Bosh sahifa',
      users: 'Foydalanuvchilar',
      teachers: "O'qituvchilar",
      students: "O'quvchilar",
      news: 'Yangiliklar',
      ratings: 'Reytinglar',
      income: 'Daromad',
      settings: 'Sozlamalar',
      profile: 'Profil',
      logout: 'Chiqish',
      totalUsers: "Jami foydalanuvchilar",
      activeUsers: 'Faol foydalanuvchilar',
      newThisWeek: "Shu haftada yangi",
      newThisMonth: "Shu oyda yangi",
      monthlyRegistrations: "Oylik ro'yxatdan o'tishlar",
      weeklyRegistrations: "Haftalik ro'yxatdan o'tishlar",
      userStatus: 'Foydalanuvchi holati',
      active: 'Faol',
      inactive: 'Nofaol',
      banned: 'Bloklangan',
      loading: 'Statistika yuklanmoqda...',
      error: 'Statistikani yuklashda xatolik',
      addNews: "Yangilik qo'shish",
      deleteNews: "Yangilikni o'chirish",
      editNews: 'Yangilikni tahrirlash',
      newsTitle: 'Sarlavha',
      newsContent: 'Mazmun',
      newsImage: 'Rasm URL',
      newsCategory: 'Kategoriya',
      save: 'Saqlash',
      cancel: 'Bekor qilish',
      confirmDelete: "O'chirishni xohlaysizmi?",
      myRating: 'Mening reytingim',
      ratingHistory: 'Reyting tarixi',
      activityPoints: 'Faollik ballari',
      attendancePoints: 'Davomat ballari',
      totalPoints: "Jami ballar",
      position: 'Pozitsiya',
      teacherRankings: "O'qituvchilar reytingi",
      myIncome: 'Mening daromadim',
      monthlyIncome: 'Oylik daromad',
      yearlyIncome: 'Yillik daromad',
      bonuses: 'Bonuslar',
      deductions: 'Ushlanmalar',
      netIncome: 'Sof daromad',
      accessDenied: 'Kirish taqiqlangan',
      noPermission: "Sizda bu bo'limni ko'rish huquqi yo'q",
      manageUsers: "Foydalanuvchilarni boshqarish",
      addUser: "Foydalanuvchi qo'shish",
      editUser: 'Foydalanuvchini tahrirlash',
      deleteUser: "Foydalanuvchini o'chirish",
      role: 'Rol',
      subject: 'Fan',
      phone: 'Telefon',
      email: 'Email',
      name: 'Ism',
      actions: 'Amallar',
      search: 'Qidirish',
      filter: 'Filtr',
      all: 'Barchasi',
      director: 'Direktor',
      viceDirector: "O'quv ishlari bo'yicha direktor o'rinbosari",
      teacher: "O'qituvchi",
      student: "O'quvchi",
    },
    common: {
      language: 'Til',
      english: 'English',
      russian: 'Русский',
      uzbek: "O'zbek",
      loading: 'Yuklanmoqda...',
      back: '← Bosh sahifaga qaytish',
      ok: 'OK',
      cancel: 'Bekor qilish',
      close: 'Yopish',
      darkMode: "Qorong'i rejim",
      lightMode: 'Yorug rejim',
    },
    roles: {
      director: 'Direktor',
      vice_director: "O'quv ishlari bo'yicha direktor o'rinbosari",
      teacher: "O'qituvchi",
      student: "O'quvchi",
    },
    subjects: {
      programming: 'Dasturlash',
      design: 'Dizayn',
      business: 'Biznes',
      hotel_business: 'Mehmonxona biznesi',
      marketing: 'Marketing',
      laboratory: 'Laboratoriya',
      english: 'Ingliz tili',
      mathematics: 'Matematika',
      russian: 'Rus tili',
      history: 'Tarix',
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  const t = (path) => {
    const keys = path.split('.');
    let value = translations[language];
    for (const key of keys) {
      value = value?.[key];
    }
    return value || path;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
